# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b27e2c3125d2db5953a26ed975bc42d7ce8d4decdd2b3b8f42f6fdd04b9a7ef790da5bb170c232ebec9779501816e06c18c0f1da5851855b375928b7d491d32

test:
  secret_key_base: 9f979f545f20690536e77ed5abe65f0470d4c4b2082aea4c816cb1caa6e6f16542e22af8b3907bfcaf74ae00ea460b62f35e75cb035a0d16856c39bd82400bcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
